# Generated by Django 3.2 on 2021-05-20 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('date', models.DateTimeField()),
                ('plink', models.TextField()),
                ('code', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
